// Generated by https://quicktype.io

class CastMovieModel {
  bool? adult;
  int? gender;
  int? id;
  String? knownForDepartment;
  String? name;
  String? originalName;
  double? popularity;
  String? profile_path;
  int? castId;
  String? character;
  String? creditId;
  int? order;

  CastMovieModel({
    this.adult,
    this.gender,
    this.id,
    this.knownForDepartment,
    this.name,
    this.originalName,
    this.popularity,
    this.profile_path,
    this.castId,
    this.character,
    this.creditId,
    this.order,
  });

  factory CastMovieModel.fromMap(Map<String, dynamic> map) {
    return CastMovieModel(
        adult: map['adult'],
        gender: map['gender'],
        id: map['id'],
        knownForDepartment: map['knownForDepartment'],
        name: map['name'],
        originalName: map['originalName'],
        popularity: map['popularity'],
        profile_path: map['profile_path'],
        castId: map['castId'],
        character: map['character'],
        creditId: map['creditId'],
        order: map['order']);
  }
}
