// Generated by https://quicktype.io

class VideoMovieModel {
  String? iso6391;
  String? iso31661;
  String? name;
  String? key;
  String? site;
  int? size;
  String? type;
  bool? official;
  String? publishedAt;
  String? id;

  VideoMovieModel({
    this.iso6391,
    this.iso31661,
    this.name,
    this.key,
    this.site,
    this.size,
    this.type,
    this.official,
    this.publishedAt,
    this.id,
  });

  factory VideoMovieModel.fromMap(Map<String, dynamic> map) {
    return VideoMovieModel(
        iso6391: map['iso6391'],
        iso31661: map['iso31661'],
        name: map['name'],
        key: map['key'],
        site: map['site'],
        size: map['size'],
        type: map['type'],
        official: map['official'],
        publishedAt: map['publishedAt'],
        id: map['id']);
  }
}
